version: '2.0'
services:
    tkw_scr_simulator:
        ports:
            - '5000:5000'
        volumes:
            - '${HOME}/Scratch/scr_data:/home/service/data'
        image: 'nhsdigitalmait/tkw_scr_simulator:0.1'
